### ISSUE TITLE
icdrama down

### ISSUE THREAD

**Issue by BlackKnightV** [aznhusband/aznhusband.github.io#27]
plugin.video.icdrama-1.9.4.zip no longer workable

**Comment by PtahX** [comment]
If you switch the base_URl in ./lib/config.py from icdrama.se icdrama.to and it will still as a quick fix

**Comment by dumbo0001** [comment]
Seems to work fine without any change or update.

**Comment by renethestudent** [comment]
It hasn't worked for me in a few weeks. Some of the errors in the log are: 

SSL: CERTIFICATE VERIFY FAILED
ERROR: URLResolver: URLError, AttributeError and Error getdirectory

**Comment by boleanly** [comment]
@renethestudent Was there a specific show/episode were you trying to watch? 

Apparently some Australian ISPs are blocking icdrama.se

**Comment by renethestudent** [comment]
Any of them, but I'm primarily looking at Korean Dramas. I'm located in the US. I tried with and without my VPN (both US based) and the links in the log are to icdrama.to .  The shows are no longer updating either. 

Earlier I tried Mother of Mine and I also tried Blessing of the Sea. Both older and newer episodes.

**Comment by boleanly** [comment]
@renethestudent It's working fine on my end. That's a weird error cause I think SSL certificates are only needed when connecting to Https sites, and Icdrama doesn't need/use a Https connection. Can you upload/paste the full log somewhere?

It might be a network redirection thing, or maybe a Kodi installation issue. You could try reinstalling that and the Icdrama addon.

**Comment by renethestudent** [comment]
I uninstalled kodi, re-installed kodi, re-installed Icdrama and I'm still getting the same errors. I have no clue how to get this log to upload, but I'm pasting a section of the log of me trying to play a video, some of the links to the video are not complete as the logviewer cut it off:

WARNING” CAddonSettings[script.module.urlresolver]:failed to parse old setting definition for “DebridLinkResolver_ts_offset” of type “int”
WARNING: Previous line repeats 1 times.
NOTICE: URResolver: Initializing URLResolver version: 3.0.35
WARNING: CPythonInvoker(10,/storage/emaulated/0/Android/data/org.xmbc.kodi/files/.kodi/addons/plugin.video.icdrama/adthe python script
“/storage/emaulated/0/Android/data/org.xmbc.kodi/files/.kodi/addons/plugin.video.icdrama/ad
has left several classes in memory that we couldn’t clean up. The classes include:
N9XBMCAddon9xbmcaddon5AddonE
WARNING: addons must not activate DialogBusy
ERROR: URLResolver: URLError Error - From: googlevideo 
Link:
https://lh3.googleuesrcontent.com/-Ews4y3fTw0o/XPlteXvawEI/AAAAAAAAAm8/8RLZLxido10x
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)> (ENCODED)
ERROR: URLResolver: URLError Error - From : Icdrama Link: 
http://www1.icdrama.to/vidembed.oSR6GHjzRYiqjq6jdYra_Q.html :<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)> (ENCODED)
ERROR: URLResolver: AttributeError Error - From: Icdrama Link:
http://www1.icdrama.to/watch-online-search-www-episode-2--156556.html: ‘NoneType’ object has no attribute ‘starts with’
WARNING: CPythonInvoker(11,/storage/emaulated/0/Android/data/org.xmbc.kodi/files/.kodi/addons/plugin.video.icdrama/adthe python script
“/storage/emaulated/0/Android/data/org.xmbc.kodi/files/.kodi/addons/plugin.video.icdrama/a
has left several classes in memory that we couldn’t clean up. The classes include: 
N9XBMCAddon9xbmcaddon5AddonE
ERROR: GetDirectory - Error getting plugin://plugin.video.icdrama/?action=mirrors&url=http%3a%2f%2fwww1.icdrama.to%2fwatc
ERROR:
CGUIMediaWindow::GetDirectory(plugin://plugin.video.icdrama/?action=mirrors&url=http%3a
failed

**Comment by boleanly** [comment]
@renethestudent Your issue might be related to [this post](https://forum.kodi.tv/showthread.php?tid=282604) from the Kodi forums. The error just shows that Python failed to verify the SSL cert from the actual video source link. It's a Google server so this shouldn't really happen. Possible fix from within this addon is to intercept the Https link and turn it into a regular Http link, or maybe just disable SSL certificate verification altogether. Not really good fixes in my opinion.

Also, are you using Kodi 17 or 18? This addon seems to run just fine with Kodi 18, and you may want to try that instead. I also updated URLResolver to the latest version at [tvaddsonco/script.module.urlresolver](https://github.com/tvaddonsco/script.module.urlresolver) so it might be needed for Kodi 18.

**Comment by renethestudent** [comment]
I'm using Kodi Leia 18.3 and I updated the URLResolver to 5.0.38 , same errors. Not sure if I mentioned this but this is through my FireTV .

**Comment by PtahX** [comment]
I just did a fresh wipe on a Win10 box with Kodi Leia 18.3 and used the //aznhusband.github.io/script.module.urlresolver/script.module.urlresolver-3.0.35.zip
and //aznhusband.github.io/plugin.video.icdrama/plugin.video.icdrama-1.9.4.zip to test it out 
no issues -- possibly something to do with the fireTV?
I didn't test it with the 5.0.38 update

**Comment by renethestudent** [comment]
Honestly not sure what it was, but I factory reset the firetv, installed Kodi 18.3, installed the icdrama repo and everything works perfectly fine again. Thank you all for your help!!!

**Comment by awfma10** [comment]
Hi, I have a similar issue .... I am running Kodi on QNAP.

I am running icdrama as an addon in Kodi 17.5 Krypton, but it has stopped working since a couple of weeks ago. I downloaded the log file and found the following logs that seem relevant to the problem: (Note: I cannot find a way to upload the entire log file otherwise I would have done so)

    12:38:08.571 T:140156686280448  NOTICE: URLResolver: Initializing URLResolver version: 3.0.35

    12:38:09.212 T:140156686280448    INFO: CPythonInvoker(4, /opt/Kodi17/.kodi/addons/plugin.video.icdrama/addon.py): script successfully run

    12:38:09.229 T:140158965581824   DEBUG: Saving fileitems [plugin://plugin.video.icdrama/]

    12:38:09.254 T:140156686280448 WARNING: CPythonInvoker(4, /opt/Kodi17/.kodi/addons/plugin.video.icdrama/addon.py): the python script "/opt/Kodi17/.kodi/addons/plugin.video.icdrama/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE

    12:38:09.254 T:140156686280448    INFO: Python script stopped

and also these logs:

    12:38:13.857 T:140156686280448   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--

                                                 - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!

                                                Error Type: <class 'urllib2.HTTPError'>

                                                Error Contents: HTTP Error 451:

                                                Traceback (most recent call last):

                                                  File "/opt/Kodi17/.kodi/addons/plugin.video.icdrama/addon.py", line 13, in <module>

                                                    action_func(**kargs)

                                                  File "/opt/Kodi17/.kodi/addons/plugin.video.icdrama/lib/actions.py", line 26, in make_dir

                                                    diritems = func(*args, **kargs)

                                                  File "/opt/Kodi17/.kodi/addons/plugin.video.icdrama/lib/actions.py", line 48, in shows

                                                    for eng_name, ori_name, show_url, image in scrapers.shows(url):

                                                  File "/opt/Kodi17/.kodi/addons/plugin.video.icdrama/lib/cache.py", line 30, in wrapped

                                                    out = func(*args, **kargs)

                                                  File "/opt/Kodi17/.kodi/addons/plugin.video.icdrama/lib/scrapers.py", line 23, in shows

                                                    soup = _soup(url)

                                                  File "/opt/Kodi17/.kodi/addons/plugin.video.icdrama/lib/cache.py", line 30, in wrapped

                                                    out = func(*args, **kargs)

                                                  File "/opt/Kodi17/.kodi/addons/plugin.video.icdrama/lib/scrapers.py", line 18, in _soup

                                                    soup = BeautifulSoup(_get(url), 'html5lib')

                                                  File "/opt/Kodi17/.kodi/addons/plugin.video.icdrama/lib/cache.py", line 30, in wrapped

                                                    out = func(*args, **kargs)

                                                  File "/opt/Kodi17/.kodi/addons/plugin.video.icdrama/lib/scrapers.py", line 12, in _get

                                                    return common.webread(url)

                                                  File "/opt/Kodi17/.kodi/addons/plugin.video.icdrama/lib/common.py", line 32, in webread

                                                    return net.http_GET(url, headers=headers).content

                                                  File "/opt/Kodi17/.kodi/addons/script.module.urlresolver/lib/urlresolver/lib/net.py", line 198, in http_GET

                                                    return self._fetch(url, headers=headers, compression=compression)

                                                  File "/opt/Kodi17/.kodi/addons/script.module.urlresolver/lib/urlresolver/lib/net.py", line 279, in _fetch

                                                    response = urllib2.urlopen(req)

                                                  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen

                                                    return _opener.open(url, data, timeout)

                                                  File "/usr/lib/python2.7/urllib2.py", line 410, in open

                                                    response = meth(req, response)

                                                  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response

                                                    'http', request, response, code, msg, hdrs)

                                                  File "/usr/lib/python2.7/urllib2.py", line 448, in error

                                                    return self._call_chain(*args)

                                                  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain

                                                    result = func(*args)

                                                  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default

                                                    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)

                                                HTTPError: HTTP Error 451:

                                                -->End of Python script error report<--

Can anyone help please?

Thanks.

**Comment by boleanly** [comment]
@awfma10 Connecting to Icdrama, probably through the .se domain, is throwing a HTTP 451 error, which seems to be an ISP block due to legal reasons. Does it show the same error if you connect to Icdrama through your browser? Try this. If you can connect to the other .to domain on your browser just fine, then you can fix the plugin by changing the base_url in config.py to the .to domain

**Comment by awfma10** [comment]
Hi boleanly, thanks for your reply.  

Indeed the problem seems to be caused by the ISP blocking the site.  I did have OpenVPN configured but for some reason it was disconnected and I was not able to establish an OpenVPN connection again. Instead I had to choose a different protocol and finally connected via PPTP. This solved the 1st problem.

The 2nd problem was that my DNS setting in Kodi was set to automatic and was pointing to the DNS of my ISP, which was blocking traffic going out to icdrama. So I had to manually point to a different DNS.

Thank you again for your prompt response!

**Comment by tvbviewer** [comment]
> If you switch the base_URl in ./lib/config.py from icdrama.se to icdrama.to it will still work as a temporary fix

Is there anyway to switch this file directly on the Firestick device?  If I look at the download files on my laptop I can see where it needs to be updated, but then I cannot get the updates back to the Firestick...  apologies for the noob question.  Thanks!

**Comment by boleanly** [comment]
@tvbviewer I don't own a Fire stick, but on a typical Android device the Kodi installation's addons folder is in the Internal Storage or SD card directory at 'Android/data/org.xbmc.kodi/files/.kodi/addons'. The .kodi folder could be hidden.

Idk how you can access the directory on the Fire stick, but if you can connect it to your computer through USB, you should be able to access the Kodi addons folder. If you can't do USB, then there are guides that show you how to install a file explorer app to let you transfer files over Wifi. I mainly saw guides using ES File Explorer, but I'd suggest X-plore File Manager cause it's more lightweight w/o ads.

Seems like @dumbo0001 and I made pull requests to change the url, but @aznhusband isn't active right now to complete the change.

**Comment by tvbviewer** [comment]
@boleanly thanks for the advice.  I'll try the file explorer route to see if I can gain access to the file there.  Otherwise, I just saw the pull request and "liked" it. Hopefully we'll see an update soon. Thanks!

**Comment by tvbviewer** [comment]
@boleanly - just to close the loop on this, I was able to make the change using ES Explorer app (seems like I already had it installed).  There was an option within the app to view the files through my laptop (it'll give you the ip / url to go to on your laptop).  Using that option, I navigated to the config.py and updated the base_url to icdrama.to and it fixed the issue.  Thanks for the advice and hope this helps anyone who recently ran into this issue!

**Comment by kcho1126** [comment]
@tvbviewer can you give me more insight on how you got it to work. I'm using a firetv currently

**Comment by tvbviewer** [comment]
@kcho1126  - yes, here are the steps I took:
1) If you don't have the ES File Explorer app already, download that.  You can DL it at your Firestick home screen.  Just search for ES File Explorer and click to DL.
2) After the install, open ES File Explorer and on the right hand side of the screen you'll see the icon for "View on PC"
3) Click on "View on PC" and it will provide you with a URL (IP address) that you can use to access all the files on your Firestick.  Type that URL into a computer that is on the same network (wifi) as your Firestick.  For example, open Google Chrome on your laptop that's on the same network and type it in there.
4) Navigate to the icdrama folder.  Follow the path:  Android/data/org.xbmc.kodi/files/.kodi/addons.  From there, you'll see another folder/link that has "icdrama" there (I don't have the full name since I'm not near the device right now).  Once you click in it, you will see a "config.py" file.  That is the file you're looking for.
5) I clicked on that "config.py" file which downloads it automatically and places it into my "Downloads" folder.  After this downloads, copy the URL in your browser now (this URL will be a direct link to the folder with all the icdrama files).
6) Open the Downloads folder and find the "config.py".  Right click on the file and edit with Notepad.  
7) When you're in edit mode, there will be a line item for base_url and the value will read "icdrama.se".  Simply change it to read "icdrama.to" (replace "se" with "to").  Then Save.  Move this file to your desktop.
8) Assuming you copied the URL in step 5, paste that URL into the File Explorer window on your laptop (this is the same window you used to search for your downloaded files).  It will now show you the same files you saw in step 5 - only difference is one view is from Chrome and the other is File Explorer.
9) Move the "config.py" file back into that File Explorer window.  You will replace the old "config.py" file with the new one you just updated (click yes to any prompts).
10) Done.  No restarts or anything necessary - just try to open up kodi/icdrama and it should play the videos.

I don't have the screen in front of me, but those are pretty much the key steps.  Let me know if that gets it working for you.  Goodluck!

**Comment by CLFNole** [comment]
I tried this and it didn’t work. My base url has only ‘ ‘ around it should it have “ “ instead?

**Comment by tvbviewer** [comment]
@CLFNole - just checked my file and the line says this:

base_url = 'http://icdrama.to'

**Comment by kcho1126** [comment]
@tvbviewer worked like a charm! thank you so much for the quick response, really appreciate it.

**Comment by CLFNole** [comment]
@tvbviewer weird wonder why it’s not working for me?  Will check it and try again.

**Comment by tvbviewer** [comment]
@kcho1126  glad it worked!
@CLFNole not sure why.  For me, when I try to go to icdrama.se on my laptop, it's a broken link so I know my ISP blocked it.  However, when I type icdrama.to on my laptop browser I have no issues.  See if you can get to icdrama.to from your laptop (ensuring you use the same network/wifi).  Goodluck!

**Comment by CLFNole** [comment]
Never mind got it thanks!

**Comment by dinisiregar** [comment]
Hi, ICdrama has not been working for me for the last several months, nothing happens when I click on anything (Korean drama, Chinese drama, etc.) The base_url is already 'http://icdrama.to'. I have uninstalled and reinstalled Kodi Leia, also uninstalled and reinstalled the ICdrama addon, but to no avail. Please help! Btw, I have zero knowledge on programming. I hope someone can help me.

**Comment by PtahX** [comment]
"Hi, ICdrama has not been working for me for the last several months, nothing happens when I click on anything (Korean drama, Chinese drama, etc.) The base_url is already 'http://icdrama.to'. I have uninstalled and reinstalled Kodi Leia, also uninstalled and reinstalled the ICdrama addon, but to no avail. Please help! Btw, I have zero knowledge on programming. I hope someone can help me."

Everything is still online and working well here, I'd make sure you are up to date on all your dependancies, kodi and of course aznhusbands latest version (1.9.6). The urlresolver and resolveurl are very important for this to work and had been running into issues untill recently. I'd suggest adding jsergios repo as well to keep your resolvers updated [https://github.com/jsergio123/zips/tree/master/repository.jsergio]

**ICDrama Basic Troubleshooting Steps**

1. Update Kodi (Current Version 8.5 - the 8.5+ and 9 pre-releases are still having some issues)
[https://kodi.tv/download](url)

2. Make sure you have the latest release of icdrama (current version 1.9.6)
[https://github.com/aznhusband/aznhusband.github.io](url)

3. Optional - Make sure you are logged into google (ResolveURL and URLResolver read that you have an authenticated google account before they’ll show you gvideo links - not related but helpful)

4. script.module.requests 
[https://kodi-addons.club/addon/script.module.requests/](url)

5. script.module.urlresolver 
[https://koditips.com/resolveurl-kodi-dependency-urlresolver-fork/](url)

6. script.module.resolveURL [https://github.com/jsergio123/zips/blob/master/script.module.resolveurl/script.module.resolveurl-5.0.37.zip](url)

8. script.module.html5lib (I doubt you will need to update this but since I'm on a roll)
[https://pypi.org/project/html5lib/](url)

9. script.module.beautifulsoup4 
[https://kodi-addons.club/addon/script.module.beautifulsoup4/](url)

10. Update the versions in the addon.xml file to whatever versions you have installed notepad++ or a text editor
`  <requires>
    <import addon="xbmc.python" version="X.X.X"/>
    <import addon="script.module.html5lib" version="X.XXX.X"/>
    <import addon="script.module.beautifulsoup4" version="X.X.X"/>
    <import addon="script.module.requests" version="X.X.X"/>
    <import addon="script.module.urlresolver" version="X.X.XX"/>
  </requires>
`
11. if that doesn't work try changing config.py `base_url = 'http://icdrama.to'` to base_url = 'http://icdrama.se' and test out each one

Good Luck! I hope that helps :)

**Comment by dinisiregar** [comment]
> "Hi, ICdrama has not been working for me for the last several months, nothing happens when I click on anything (Korean drama, Chinese drama, etc.) The base_url is already 'http://icdrama.to'. I have uninstalled and reinstalled Kodi Leia, also uninstalled and reinstalled the ICdrama addon, but to no avail. Please help! Btw, I have zero knowledge on programming. I hope someone can help me."
> 
> @dinisiregar
> Everything is still online and working well here, I'd make sure you are up to date on all your dependancies, kodi and of course aznhusbands latest version (1.9.6). The urlresolver and resolveurl are very important for this to work and had been running into issues untill recently. I'd suggest adding jsergios repo as well to keep your resolvers updated [https://github.com/jsergio123/zips/tree/master/repository.jsergio](url)
> 
> **ICDrama Basic Troubleshooting Steps**
> 
> 1. Update Kodi (Current Version 8.5 - the 8.5+ and 9 pre-releases are still having some issues)
>    [https://kodi.tv/download](url)
> 2. Make sure you have the latest release of icdrama (current version 1.9.6)
>    [https://github.com/aznhusband/aznhusband.github.io](url)
> 3. Optional - Make sure you are logged into google (ResolveURL and URLResolver read that you have an authenticated google account before they’ll show you gvideo links - not related but helpful)
> 4. script.module.requests
>    [https://kodi-addons.club/addon/script.module.requests/](url)
> 5. script.module.urlresolver
>    [https://koditips.com/resolveurl-kodi-dependency-urlresolver-fork/](url)
> 6. script.module.resolveURL [https://github.com/jsergio123/zips/blob/master/script.module.resolveurl/script.module.resolveurl-5.0.37.zip](url)
> 7. script.module.html5lib (I doubt you will need to update this but since I'm on a roll)
>    [https://pypi.org/project/html5lib/](url)
> 8. script.module.beautifulsoup4
>    [https://kodi-addons.club/addon/script.module.beautifulsoup4/](url)
> 9. Update the versions in the addon.xml file to whatever versions you have installed notepad++ or a text editor
>    `  <requires> <import addon="xbmc.python" version="X.X.X"/> <import addon="script.module.html5lib" version="X.XXX.X"/> <import addon="script.module.beautifulsoup4" version="X.X.X"/> <import addon="script.module.requests" version="X.X.X"/> <import addon="script.module.urlresolver" version="X.X.XX"/>   </requires>`
> 10. if that doesn't work try changing config.py `base_url = 'http://icdrama.to'` to base_url = 'http://icdrama.se' and test out each one
> 
> Good Luck! I hope that helps :)

Hi, thanks for your trouble. I did all the steps, and when I launch kodi, it says that the beautifulsoup4 script is not compatible, and I still can't use ICdrama. What should I do next?

**Comment by PtahX** [comment]
@dinisiregar
I’m not sure what platform you are running Kodi on but if you can get a log file of what isn’t working and post it that would be very helpful. 

I just had a look at my Kodi box. I am running beautifulsoup 4.6.3 and I just checked out 4.3.2 which still seems to be working. I'd assume either of those should be fine if the 4.7+ isn't working. I believe the packed version in ICDrama was 4.3.2 so I doubt that is going to be the problem regardless. 

Next step will definitely be to grab the error log, then we can see where the problem is 
you can see the dependencies that Icdrama is calling for in add-ons – The top left box – my add-ons – all – Icdrama  - dependancies button. 

I just reinstalled on my second box - here is what i'm showing on a working copy
Kodi 18.5
script.module.html5lib -  0.999.0
script.module.beautifulsoup4 -  4.3.2
script.module.requests - 2.9.1
script.module.urlresolver - 3.0.34
plugin.video.youtube - 0.0.0
script.module.python.twitch - 0.0.0
plugin.video.gdrive 0.0.0
Inputstream Helper 0.2.2
six 1.11.0
requests 2.12.4
pysocks 1.6.8
urllib3 1.22
chardet 3.0.4
idna 2.6
certifi 2017.07.27.1
inet_pton NA

**Comment by BlackKnightV** [comment]
Hi,

I noticed icdrama is not updated with frequent new movies and Chinese
dramas. It's full of old movies and dramas though. Any advise? Thanks.

Regards,
Edward

**Comment by dinisiregar** [comment]
> @dinisiregar
> Next install all those updates manually of via a repo - see if it works after a reboot
> **if not next steps are below**
> 
> I’m not sure what platform you are running Kodi on but if you can get a log file of what isn’t working and post it that would be very helpful.
> 
> I just had a look at my Kodi box. I am running beautifulsoup 4.6.3 and I just checked out 4.3.2 which still seems to be working. I'd assume either of those should be fine if the 4.7+ isn't working. I believe the packed version in ICDrama was 4.3.2 so I doubt that is going to be the problem regardless.
> 
> Next step will definitely be to grab the error log, then we can see where the problem is
> you can see the dependencies that Icdrama is calling for in add-ons – The top left box – my add-ons – all – Icdrama - dependancies button.
> 
> I just reinstalled on my second box - here is what i'm showing on a working copy
> Kodi 18.5
> script.module.html5lib - 0.999.0
> script.module.beautifulsoup4 - 4.3.2
> script.module.requests - 2.9.1
> script.module.urlresolver - 3.0.35
> plugin.video.youtube - 0.0.0
> script.module.python.twitch - 0.0.0
> plugin.video.gdrive 0.0.0
> Inputstream Helper 0.2.2
> six 1.11.0
> requests 2.12.4
> pysocks 1.6.8
> urllib3 1.22
> chardet 3.0.4
> idna 2.6
> certifi 2017.07.27.1
> inet_pton NA
> 
> If all else fails step 9 & 10 above are where you get to be creative rezip Icdrama with the EXACT same name (Or change the xml data to match) then uninstall both the aznhusband repo and also the Icdrama app and reinstall locally with your own version.You can probably do this step in the ES Explorer app as well - might be easier.
> 
> I don't expect you will need to do the last steps here but in a pinch this would be my next move

Ok before I'm going to do the last step, out of all the dependencies you listed on a working copy, I'm missing plugin.video.gdrive 0.0.0. Could that be the problem? Where do I get that? And I'm sorry this image must look like shite, but the kodi is on my tv so I don't know how else I'm going to get the error log file unless I took a picture of it using my phone.

![WhatsApp Image 2020-01-18 at 08 15 48](https://user-images.githubusercontent.com/59866752/72656559-bd49d480-39ce-11ea-832c-920d57b95ad8.jpeg)

**Comment by PtahX** [comment]
It's still posible that you have more than one issue there but your problem seems to be with BS4 (Beautiful Soup 4)  Try adding the following Source [https://i-a-c.github.io/] update beautful soup 4 see if that sorts you out  (That's the Exodus-redux repo) here is a tutorial if you need it [https://mykodiaddons.com/exodus-redux/](url)

**Comment by dinisiregar** [comment]
> It's still posible that you have more than one issue there but your problem seems to be with BS4 (Beautiful Soup 4) Try adding the following Source [https://i-a-c.github.io/] update beautful soup 4 see if that sorts you out (That's the Exodus-redux repo) here is a tutorial if you need it [https://mykodiaddons.com/exodus-redux/](url)

It's still not working. I've come to the point where I feel my problem annoys people haha

**Comment by yewhoongng** [comment]
> > It's still posible that you have more than one issue there but your problem seems to be with BS4 (Beautiful Soup 4) Try adding the following Source [https://i-a-c.github.io/] update beautful soup 4 see if that sorts you out (That's the Exodus-redux repo) here is a tutorial if you need it [https://mykodiaddons.com/exodus-redux/](url)
> 
> It's still not working. I've come to the point where I feel my problem annoys people haha

Had a similar issue resolved after changing my DNS setting. need to configure yr IP address to use a primary DNS of 1.1.1.1 instead of automatically provided by your ISP. Lots of ISP in Australia uses DNS blocking which means your device cant open icdrama.to if youre using their DNS.

**Comment by BlackKnightV** [comment]
No longer using this. So annoying on the problems and it's shows are not
updated at all.
