### ISSUE TITLE
Error when trying to playback: object of type 'int' has no len()

### ISSUE THREAD

**Issue by wilsonfan** [aznhusband/aznhusband.github.io#4]
There appears to be a problem in videobug.py, which is causing a problem when trying to load videos in icdrama: 
```
ERROR: URLResolver: TypeError Error - From: Videobug Link: http://videobug.se/v/PWuFJdznTMnwvM9vY0Vbtw: object of type 'int' has no len()
DEBUG: URLResolver: Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urlresolver/lib/urlresolver/hmf.py", line 181, in resolve
                                                stream_url = resolver.get_media_url(self._host, self._media_id)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.icdrama/lib/resolvers/videobug.py", line 29, in get_media_url
                                                streams = self._extract_streams(response)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.icdrama/lib/resolvers/videobug.py", line 62, in _extract_streams
                                                streams = method(response)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.icdrama/lib/resolvers/videobug.py", line 85, in __method1
                                                if len(d) > 10:
                                            TypeError: object of type 'int' has no len()
```

Please let me know if you need further details. Thanks!

**Comment by aznhusband** [comment]
dumb0001 just came up with the fix.  I'll release the new version shortly
